version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  probe-node:
    build: ./probe
    volumes:
      - ./probe:/app
    environment:
      - PROBEOPS_BACKEND_URL=https://probeops.com
      - PROBEOPS_API_KEY=sample-api-key
