"""Make all timestamps timezone-aware

Revision ID: 8fdef82eb92b
Revises: b06c45bd94a4
Create Date: 2025-05-26 19:11:45.231487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fdef82eb92b'
down_revision: Union[str, None] = 'b06c45bd94a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_scheduled_probes_name'), 'scheduled_probes', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_probes_name'), table_name='scheduled_probes')
    # ### end Alembic commands ###
