"""Add unique constraint to scheduled_probe.name and cascade to probe_results

Revision ID: b06c45bd94a4
Revises: 9ab50cf949d2
Create Date: 2025-05-26 16:01:35.252665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06c45bd94a4'
down_revision: Union[str, None] = '9ab50cf949d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
